<?php

namespace AppBundle\Repository;

/**
 * IcecreamItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcecreamItemRepository extends \Doctrine\ORM\EntityRepository
{
}
