<?php

namespace AppBundle\Repository;

/**
 * ToppingItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToppingItemRepository extends \Doctrine\ORM\EntityRepository
{
}
